@server = http://localhost
@port = 3000
@resource = api
@url = {{server}}:{{port}}/{{resource}}

###############################################

// Test: Get all miun courses
// Expected HTTP response status code: 200
// Expected response: an object (json) with an array with all courses (including subject for each course)
// {"courses": [{}, {}, ...]}
GET {{url}}/courses

###############################################

// Test: Get a miun course that exists
// Expected HTTP response status code: 200
// Expected response: a course object (json) with course data, including subject
// {"courseCode": "DT190G","subjectCode": "DTA","level": "GR","progression": "B","name": "Javascriptbaserad webbutveckling","points": 7.5,"institutionCode": "DSV","subject": "Datateknik"}
GET {{url}}/courses/DT190G

###############################################

// Test: Get a miun course that does not exists
// Expected HTTP response status code: 200
// Expected response: an empty object (json)
// {}
GET {{url}}/courses/DT000G

###############################################

// Test: Get all "my courses"
// Expected HTTP response status code: 200
// Expected response: an object (json) with an array with all my courses and data from corresponding miun courses
// {"myCourses": [{}, {}, ...]}
GET {{url}}/my/courses

###############################################

// Test: Get a my course that exists
// Expected HTTP response status code: 200
// Expected response: a my course object (json) with status and all data from corresponding miun course
// {"courseCode": "DT190G", "status": 0, "subjectCode": "DTA","level": "GR","progression": "B","name": "Javascriptbaserad webbutveckling","points": 7.5,"institutionCode": "DSV","subject": "Datateknik"}
GET {{url}}/my/courses/DT190G

###############################################

// Test: Get a my course that does not exists
// Expected HTTP response status code: 200
// Expected response: an empty object (json)
// {}
GET {{url}}/my/courses/DT000G

###############################################

// Test: Post (add) a my course that is not a Miun course
// Expected HTTP response status code: 404
// Expected response: an object (json) with an error message stating that the course does not exist
// {"error":"an_error_message"}
POST {{url}}/my/courses HTTP/1.1
content-type: application/json

{
   "courseCode": "DT000G",
   "status": 1
}

###############################################

// Test: Post (add) a my course that is a Miun course db AND NOT already in 'my courses'
// Expected HTTP response status code: 201
// Expected response: an object (json) with the appropriate data of your choice
POST {{url}}/my/courses HTTP/1.1
content-type: application/json

{
   "courseCode": "DT005U",
   "status": 1
}

###############################################

// Test: Post (add) a my course that is a Miun course db AND already in 'my courses'
// Expected HTTP response status code: 409
// Expected response: an object (json) with an error message stating that the my course already exist
// {"error":"an_error_message"}
POST {{url}}/my/courses HTTP/1.1
content-type: application/json

{
   "courseCode": "DT005U",
   "status": 0
}

###############################################

// Test: Put (update) a my course that exists
// Expected HTTP response status code: 200
// Expected response: an object (json) with the appropriate data of your choice
PUT {{url}}/my/courses/DT005U HTTP/1.1
content-type: application/json

{
   "status": 99
}

###############################################

// Test: Put (update) a my course that does not exists
// Expected HTTP response status code: 404
// Expected response: an object (json) with an error message stating that the my course does not exist
// {"error":"an_error_message"}
PUT {{url}}/my/courses/DT000G HTTP/1.1
content-type: application/json

{
   "status": 99
}

###############################################

// Test: Delete a my course that does not exists
// Expected HTTP response status code: 404
// Expected response: an object (json) with an error message stating that the my course does not exist
// {"error":"an_error_message"}
DELETE {{url}}/my/courses/DT000G

###############################################

// Test: Delete a my course that exists
// Expected HTTP response status code: 200
// Expected response: an object (json) with the appropriate data of your choice
// {"error":"an_error_message"}
DELETE {{url}}/my/courses/DT005U

###############################################

// Test: Get all subjects
// Expected HTTP response status code: 200
// Expected response: an object (json) with an array with all subjects
// {"subjects": [{}, {}, ...]}
GET {{url}}/subjects

###############################################

// Test: Get a subject that exists
// Expected HTTP response status code: 200
// Expected response: a subject object (json) with subject data
// {"subjectCode": "DTA","subject": "Datateknik","preamble": ".....", "bodyText": "....","language": "..."}
GET {{url}}/subjects/dta

###############################################

// Test: Get a subject that does not exists
// Expected HTTP response status code: 200
// Expected response: an empty object (json)
// {}
GET {{url}}/subjects/abc